# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-12 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ts', models.DateField(default=datetime.datetime.now)),
                ('text', models.TextField()),
            ],
        ),
    ]
