# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-13 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='ts',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
